package storage

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/fuhrdan/TelemetryForge/internal/domain"
	"github.com/fuhrdan/TelemetryForge/internal/schema"
	"github.com/fuhrdan/TelemetryForge/internal/security"
	"github.com/jackc/pgx/v5"
)

const (
	requiredSampleFloor = int64(20)
	requiredPercent     = int64(95)
)

// ObserveSchema records one idempotent schema observation and returns the
// resulting registry state plus any drift findings generated by that event.
func (store *PostgresStore) ObserveSchema(
	ctx context.Context,
	event domain.Event,
	description schema.Description,
) (schema.RegistryEntry, []schema.Drift, error) {
	if strings.TrimSpace(event.ID) == "" {
		return schema.RegistryEntry{}, nil, errors.New("schema observation requires event ID")
	}
	if description.Source == "" || description.EventType == "" || description.DeclaredVersion == "" {
		return schema.RegistryEntry{}, nil, errors.New("schema observation requires source, event type, and declared version")
	}

	tx, err := store.pool.Begin(ctx)
	if err != nil {
		return schema.RegistryEntry{}, nil, fmt.Errorf("begin schema observation: %w", err)
	}
	defer func() { _ = tx.Rollback(context.Background()) }()

	tenantID := tenantForEvent(ctx, event)
	lockKey := tenantID + "|" + description.Source + "|" + description.EventType
	if _, err := tx.Exec(ctx, `SELECT pg_advisory_xact_lock(hashtextextended($1, 0))`, lockKey); err != nil {
		return schema.RegistryEntry{}, nil, fmt.Errorf("lock schema registry identity: %w", err)
	}

	var observedAt time.Time
	err = tx.QueryRow(ctx, `
		INSERT INTO schema_observations
			(tenant_id, event_id, source, event_type, declared_version, schema_url, fingerprint)
		VALUES ($1,$2,$3,$4,$5,$6,$7)
		ON CONFLICT (tenant_id, event_id) DO NOTHING
		RETURNING observed_at`,
		tenantID, event.ID, description.Source, description.EventType,
		description.DeclaredVersion, description.SchemaURL, description.Fingerprint,
	).Scan(&observedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		entry, loadErr := loadSchemaEntryTx(
			ctx, tx, tenantID, description.Source, description.EventType,
			description.DeclaredVersion, false,
		)
		if loadErr != nil {
			return schema.RegistryEntry{}, nil, loadErr
		}
		if err := tx.Commit(ctx); err != nil {
			return schema.RegistryEntry{}, nil, fmt.Errorf("commit duplicate schema observation: %w", err)
		}
		return entry, nil, nil
	}
	if err != nil {
		return schema.RegistryEntry{}, nil, fmt.Errorf("insert schema observation: %w", err)
	}

	entry, err := loadSchemaEntryTx(
		ctx, tx, tenantID, description.Source, description.EventType,
		description.DeclaredVersion, true,
	)
	newVersion := errors.Is(err, pgx.ErrNoRows)
	if err != nil && !newVersion {
		return schema.RegistryEntry{}, nil, err
	}

	var drifts []schema.Drift
	if newVersion {
		entry = newRegistryEntry(tenantID, description, observedAt)

		previous, previousErr := loadPreviousSchemaEntryTx(
			ctx, tx, tenantID, description.Source, description.EventType,
			description.DeclaredVersion,
		)
		if previousErr != nil && !errors.Is(previousErr, pgx.ErrNoRows) {
			return schema.RegistryEntry{}, nil, previousErr
		}
		if previousErr == nil {
			versionDiff := schema.Diff(previous, entry)
			for _, change := range versionDiff.Changes {
				drifts = append(drifts, schema.Drift{
					TenantID: tenantID, Source: entry.Source, EventType: entry.EventType,
					DeclaredVersion: entry.DeclaredVersion, Severity: change.Severity,
					Kind: "version_" + change.Kind, Path: change.Path,
					PreviousType: change.PreviousType, CurrentType: change.CurrentType,
					Message:   fmt.Sprintf("schema version %s -> %s: %s", previous.DeclaredVersion, entry.DeclaredVersion, change.Message),
					FirstSeen: observedAt, LastSeen: observedAt, Occurrences: 1,
				})
			}
		}
		for _, finding := range description.Semantic {
			drifts = append(drifts, semanticDrift(tenantID, description, finding, observedAt))
		}
		if description.Truncated {
			drifts = append(drifts, truncatedDrift(tenantID, description, observedAt))
		}
		entry.Health = healthFor(entry.Health, drifts)
		entry.Fingerprint = schema.Fingerprint(fieldsFromStates(entry.Fields))
		if err := insertSchemaEntryTx(ctx, tx, entry); err != nil {
			return schema.RegistryEntry{}, nil, err
		}
	} else {
		entry, drifts = updateRegistryEntry(entry, description, observedAt)
		if err := updateSchemaEntryTx(ctx, tx, entry); err != nil {
			return schema.RegistryEntry{}, nil, err
		}
	}

	for index := range drifts {
		if err := upsertSchemaDriftTx(ctx, tx, &drifts[index]); err != nil {
			return schema.RegistryEntry{}, nil, err
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return schema.RegistryEntry{}, nil, fmt.Errorf("commit schema observation: %w", err)
	}
	return entry, drifts, nil
}

// ListSchemas returns the newest observed version for each source/type.
func (store *PostgresStore) ListSchemas(ctx context.Context, limit int) ([]schema.RegistryEntry, error) {
	if limit < 1 || limit > 500 {
		limit = 100
	}
	rows, err := store.pool.Query(ctx, `
		SELECT tenant_id, source, event_type, declared_version, schema_url, fingerprint, health,
		       first_seen, last_seen, observation_count, field_count,
		       required_field_count, fields, semantic_findings
		  FROM (
		        SELECT DISTINCT ON (source, event_type)
		               tenant_id, source, event_type, declared_version, schema_url, fingerprint,
		               health, first_seen, last_seen, observation_count, field_count,
		               required_field_count, fields, semantic_findings
		          FROM schema_registry
		         WHERE tenant_id = $1
		         ORDER BY source, event_type, last_seen DESC
		       ) latest
		 ORDER BY last_seen DESC
		 LIMIT $2`, security.TenantID(ctx), limit)
	if err != nil {
		return nil, fmt.Errorf("list schemas: %w", err)
	}
	defer rows.Close()

	entries := make([]schema.RegistryEntry, 0, limit)
	for rows.Next() {
		entry, err := scanSchemaEntry(rows)
		if err != nil {
			return nil, err
		}
		entries = append(entries, entry)
	}
	return entries, rows.Err()
}

// SchemaHistory returns all observed declared versions for one source/type.
func (store *PostgresStore) SchemaHistory(
	ctx context.Context,
	source string,
	eventType string,
) ([]schema.RegistryEntry, error) {
	rows, err := store.pool.Query(ctx, `
		SELECT tenant_id, source, event_type, declared_version, schema_url, fingerprint, health,
		       first_seen, last_seen, observation_count, field_count,
		       required_field_count, fields, semantic_findings
		  FROM schema_registry
		 WHERE tenant_id = $1
		   AND source = $2
		   AND event_type = $3
		 ORDER BY first_seen DESC`,
		security.TenantID(ctx), strings.TrimSpace(source), strings.TrimSpace(eventType))
	if err != nil {
		return nil, fmt.Errorf("query schema history: %w", err)
	}
	defer rows.Close()

	entries := make([]schema.RegistryEntry, 0)
	for rows.Next() {
		entry, err := scanSchemaEntry(rows)
		if err != nil {
			return nil, err
		}
		entries = append(entries, entry)
	}
	return entries, rows.Err()
}

// ListSchemaDrifts returns newest-first deduplicated drift findings.
func (store *PostgresStore) ListSchemaDrifts(ctx context.Context, limit int) ([]schema.Drift, error) {
	if limit < 1 || limit > 500 {
		limit = 100
	}
	rows, err := store.pool.Query(ctx, `
		SELECT tenant_id, source, event_type, declared_version, signature, severity,
		       kind, path, previous_type, current_type, message, first_seen,
		       last_seen, occurrences
		  FROM schema_drift_findings
		 WHERE tenant_id = $1
		 ORDER BY last_seen DESC
		 LIMIT $2`, security.TenantID(ctx), limit)
	if err != nil {
		return nil, fmt.Errorf("list schema drift: %w", err)
	}
	defer rows.Close()

	drifts := make([]schema.Drift, 0, limit)
	for rows.Next() {
		var drift schema.Drift
		var previousType string
		var currentType string
		if err := rows.Scan(
			&drift.TenantID, &drift.Source, &drift.EventType, &drift.DeclaredVersion,
			&drift.Signature, &drift.Severity, &drift.Kind, &drift.Path,
			&previousType, &currentType, &drift.Message,
			&drift.FirstSeen, &drift.LastSeen, &drift.Occurrences,
		); err != nil {
			return nil, fmt.Errorf("scan schema drift: %w", err)
		}
		drift.PreviousType = schema.ValueType(previousType)
		drift.CurrentType = schema.ValueType(currentType)
		drifts = append(drifts, drift)
	}
	return drifts, rows.Err()
}

// SchemaDiff compares two persisted declared versions.
func (store *PostgresStore) SchemaDiff(
	ctx context.Context,
	source string,
	eventType string,
	fromVersion string,
	toVersion string,
) (schema.VersionDiff, error) {
	tenantID := security.TenantID(ctx)
	from, err := loadSchemaEntryPool(ctx, store, tenantID, source, eventType, fromVersion)
	if err != nil {
		return schema.VersionDiff{}, fmt.Errorf("load from schema version: %w", err)
	}
	to, err := loadSchemaEntryPool(ctx, store, tenantID, source, eventType, toVersion)
	if err != nil {
		return schema.VersionDiff{}, fmt.Errorf("load to schema version: %w", err)
	}
	return schema.Diff(from, to), nil
}

// PruneSchemaObservations removes old per-event idempotency ledger rows while
// preserving the accumulated registry, drift history, and schema versions.
func (store *PostgresStore) PruneSchemaObservations(ctx context.Context, before time.Time) (int64, error) {
	if before.IsZero() {
		return 0, errors.New("schema observation prune cutoff is required")
	}
	tag, err := store.pool.Exec(ctx, `
		DELETE FROM schema_observations
		 WHERE tenant_id = $1
		   AND observed_at < $2`, security.TenantID(ctx), before.UTC())
	if err != nil {
		return 0, fmt.Errorf("prune schema observations: %w", err)
	}
	return tag.RowsAffected(), nil
}

func newRegistryEntry(tenantID string, description schema.Description, observedAt time.Time) schema.RegistryEntry {
	fields := make([]schema.FieldState, 0, len(description.Fields))
	for _, field := range description.Fields {
		fields = append(fields, schema.FieldState{
			Field: field, FirstSeen: observedAt, LastSeen: observedAt, SeenCount: 1,
		})
	}
	health := "healthy"
	if len(description.Semantic) > 0 || description.Truncated {
		health = "warning"
	}
	return schema.RegistryEntry{
		TenantID: tenantID, Source: description.Source, EventType: description.EventType,
		DeclaredVersion: description.DeclaredVersion, SchemaURL: description.SchemaURL,
		Fingerprint: description.Fingerprint,
		Health:      health, FirstSeen: observedAt, LastSeen: observedAt, ObservationCount: 1,
		FieldCount: len(fields), Fields: fields, Semantic: description.Semantic,
	}
}

func updateRegistryEntry(
	entry schema.RegistryEntry,
	description schema.Description,
	observedAt time.Time,
) (schema.RegistryEntry, []schema.Drift) {
	previousObservations := entry.ObservationCount
	states := make(map[string]*schema.FieldState, len(entry.Fields))
	for index := range entry.Fields {
		states[entry.Fields[index].Path] = &entry.Fields[index]
	}

	current := make(map[string]schema.Field, len(description.Fields))
	drifts := make([]schema.Drift, 0)
	for _, field := range description.Fields {
		current[field.Path] = field
		state, exists := states[field.Path]
		if !exists {
			if len(entry.Fields) >= schema.MaxRegistryFields {
				if !hasDriftKind(drifts, "registry_field_limit") {
					drifts = append(drifts, schema.Drift{
						TenantID: entry.TenantID, Source: entry.Source, EventType: entry.EventType,
						DeclaredVersion: entry.DeclaredVersion, Severity: "warning", Kind: "registry_field_limit",
						Message:   fmt.Sprintf("schema registry reached the %d-field safety limit; additional new paths are not accumulated", schema.MaxRegistryFields),
						FirstSeen: observedAt, LastSeen: observedAt, Occurrences: 1,
					})
				}
				continue
			}
			entry.Fields = append(entry.Fields, schema.FieldState{
				Field: field, FirstSeen: observedAt, LastSeen: observedAt, SeenCount: 1,
			})
			drifts = append(drifts, schema.Drift{
				TenantID: entry.TenantID, Source: entry.Source, EventType: entry.EventType,
				DeclaredVersion: entry.DeclaredVersion, Severity: "info", Kind: "field_added",
				Path: field.Path, CurrentType: field.Type,
				Message:   fmt.Sprintf("new field %s observed without a declared schema version change", field.Path),
				FirstSeen: observedAt, LastSeen: observedAt, Occurrences: 1,
			})
			continue
		}

		state.SeenCount++
		state.LastSeen = observedAt
		if state.Type != field.Type {
			state.ConflictCount++
			drifts = append(drifts, schema.Drift{
				TenantID: entry.TenantID, Source: entry.Source, EventType: entry.EventType,
				DeclaredVersion: entry.DeclaredVersion, Severity: "breaking", Kind: "type_changed",
				Path: field.Path, PreviousType: state.Type, CurrentType: field.Type,
				Message:   fmt.Sprintf("field %s changed type from %s to %s without a declared schema version change", field.Path, state.Type, field.Type),
				FirstSeen: observedAt, LastSeen: observedAt, Occurrences: 1,
			})
		}
	}

	for index := range entry.Fields {
		state := &entry.Fields[index]
		if _, exists := current[state.Path]; exists {
			continue
		}
		wasRequired := previousObservations >= requiredSampleFloor &&
			state.SeenCount*100 >= previousObservations*requiredPercent
		if wasRequired {
			drifts = append(drifts, schema.Drift{
				TenantID: entry.TenantID, Source: entry.Source, EventType: entry.EventType,
				DeclaredVersion: entry.DeclaredVersion, Severity: "breaking", Kind: "required_field_missing",
				Path: state.Path, PreviousType: state.Type,
				Message:   fmt.Sprintf("field %s was present in at least 95%% of established observations and is now missing", state.Path),
				FirstSeen: observedAt, LastSeen: observedAt, Occurrences: 1,
			})
		}
	}

	if description.SchemaURL != "" {
		if entry.SchemaURL != "" && entry.SchemaURL != description.SchemaURL {
			drifts = append(drifts, schema.Drift{
				TenantID: entry.TenantID, Source: entry.Source, EventType: entry.EventType,
				DeclaredVersion: entry.DeclaredVersion, Severity: "warning", Kind: "schema_url_changed",
				Message:   fmt.Sprintf("OpenTelemetry schema_url changed from %s to %s without an application schema_version change", entry.SchemaURL, description.SchemaURL),
				FirstSeen: observedAt, LastSeen: observedAt, Occurrences: 1,
			})
		}
		entry.SchemaURL = description.SchemaURL
	}

	for _, finding := range description.Semantic {
		drifts = append(drifts, semanticDrift(entry.TenantID, description, finding, observedAt))
	}
	if description.Truncated {
		drifts = append(drifts, truncatedDrift(entry.TenantID, description, observedAt))
	}

	entry.ObservationCount++
	entry.LastSeen = observedAt
	entry.Semantic = mergeSemanticFindings(entry.Semantic, description.Semantic)
	entry.RequiredFieldCount = 0
	for index := range entry.Fields {
		state := &entry.Fields[index]
		state.Required = entry.ObservationCount >= requiredSampleFloor &&
			state.SeenCount*100 >= entry.ObservationCount*requiredPercent
		if state.Required {
			entry.RequiredFieldCount++
		}
	}
	sort.Slice(entry.Fields, func(i, j int) bool { return entry.Fields[i].Path < entry.Fields[j].Path })
	entry.FieldCount = len(entry.Fields)
	entry.Fingerprint = schema.Fingerprint(fieldsFromStates(entry.Fields))
	entry.Health = healthFor(entry.Health, drifts)
	return entry, drifts
}

func hasDriftKind(drifts []schema.Drift, kind string) bool {
	for _, drift := range drifts {
		if drift.Kind == kind {
			return true
		}
	}
	return false
}

func semanticDrift(
	tenantID string,
	description schema.Description,
	finding schema.SemanticFinding,
	observedAt time.Time,
) schema.Drift {
	message := finding.Message
	if finding.Replacement != "" {
		message += "; prefer " + finding.Replacement
	}
	return schema.Drift{
		TenantID: tenantID, Source: description.Source, EventType: description.EventType,
		DeclaredVersion: description.DeclaredVersion, Severity: finding.Severity,
		Kind: finding.Kind, Path: finding.Path, Message: message,
		FirstSeen: observedAt, LastSeen: observedAt, Occurrences: 1,
	}
}

func truncatedDrift(tenantID string, description schema.Description, observedAt time.Time) schema.Drift {
	return schema.Drift{
		TenantID: tenantID, Source: description.Source, EventType: description.EventType,
		DeclaredVersion: description.DeclaredVersion, Severity: "warning", Kind: "schema_truncated",
		Message:   "event shape exceeded Schema Intelligence depth/field bounds; registry view was truncated",
		FirstSeen: observedAt, LastSeen: observedAt, Occurrences: 1,
	}
}

func healthFor(current string, drifts []schema.Drift) string {
	health := current
	if health == "" {
		health = "healthy"
	}
	for _, drift := range drifts {
		switch drift.Severity {
		case "breaking":
			return "breaking"
		case "warning":
			if health == "healthy" {
				health = "warning"
			}
		}
	}
	return health
}

func fieldsFromStates(states []schema.FieldState) []schema.Field {
	fields := make([]schema.Field, 0, len(states))
	for _, state := range states {
		fields = append(fields, state.Field)
	}
	return fields
}

func mergeSemanticFindings(existing, current []schema.SemanticFinding) []schema.SemanticFinding {
	result := append([]schema.SemanticFinding(nil), existing...)
	seen := make(map[string]struct{}, len(result))
	for _, finding := range result {
		seen[finding.Path+"|"+finding.Kind] = struct{}{}
	}
	for _, finding := range current {
		key := finding.Path + "|" + finding.Kind
		if _, exists := seen[key]; exists {
			continue
		}
		seen[key] = struct{}{}
		result = append(result, finding)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Path < result[j].Path })
	return result
}

func insertSchemaEntryTx(ctx context.Context, tx pgx.Tx, entry schema.RegistryEntry) error {
	fields, semantic, err := encodeSchemaJSON(entry)
	if err != nil {
		return err
	}
	_, err = tx.Exec(ctx, `
		INSERT INTO schema_registry
			(tenant_id, source, event_type, declared_version, schema_url, fingerprint, health,
			 first_seen, last_seen, observation_count, field_count,
			 required_field_count, fields, semantic_findings)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb)`,
		entry.TenantID, entry.Source, entry.EventType, entry.DeclaredVersion,
		entry.SchemaURL, entry.Fingerprint, entry.Health, entry.FirstSeen, entry.LastSeen,
		entry.ObservationCount, entry.FieldCount, entry.RequiredFieldCount,
		string(fields), string(semantic))
	if err != nil {
		return fmt.Errorf("insert schema registry: %w", err)
	}
	return nil
}

func updateSchemaEntryTx(ctx context.Context, tx pgx.Tx, entry schema.RegistryEntry) error {
	fields, semantic, err := encodeSchemaJSON(entry)
	if err != nil {
		return err
	}
	_, err = tx.Exec(ctx, `
		UPDATE schema_registry
		   SET schema_url = $5,
		       fingerprint = $6,
		       health = $7,
		       last_seen = $8,
		       observation_count = $9,
		       field_count = $10,
		       required_field_count = $11,
		       fields = $12::jsonb,
		       semantic_findings = $13::jsonb
		 WHERE tenant_id = $1
		   AND source = $2
		   AND event_type = $3
		   AND declared_version = $4`,
		entry.TenantID, entry.Source, entry.EventType, entry.DeclaredVersion,
		entry.SchemaURL, entry.Fingerprint, entry.Health, entry.LastSeen, entry.ObservationCount,
		entry.FieldCount, entry.RequiredFieldCount, string(fields), string(semantic))
	if err != nil {
		return fmt.Errorf("update schema registry: %w", err)
	}
	return nil
}

func encodeSchemaJSON(entry schema.RegistryEntry) ([]byte, []byte, error) {
	fields, err := json.Marshal(entry.Fields)
	if err != nil {
		return nil, nil, fmt.Errorf("encode schema fields: %w", err)
	}
	semantic, err := json.Marshal(entry.Semantic)
	if err != nil {
		return nil, nil, fmt.Errorf("encode semantic findings: %w", err)
	}
	return fields, semantic, nil
}

func loadSchemaEntryTx(
	ctx context.Context,
	tx pgx.Tx,
	tenantID string,
	source string,
	eventType string,
	version string,
	forUpdate bool,
) (schema.RegistryEntry, error) {
	query := `
		SELECT tenant_id, source, event_type, declared_version, schema_url, fingerprint, health,
		       first_seen, last_seen, observation_count, field_count,
		       required_field_count, fields, semantic_findings
		  FROM schema_registry
		 WHERE tenant_id = $1 AND source = $2 AND event_type = $3 AND declared_version = $4`
	if forUpdate {
		query += " FOR UPDATE"
	}
	return scanSchemaEntryRow(tx.QueryRow(ctx, query, tenantID, source, eventType, version))
}

func loadPreviousSchemaEntryTx(
	ctx context.Context,
	tx pgx.Tx,
	tenantID string,
	source string,
	eventType string,
	excludeVersion string,
) (schema.RegistryEntry, error) {
	return scanSchemaEntryRow(tx.QueryRow(ctx, `
		SELECT tenant_id, source, event_type, declared_version, schema_url, fingerprint, health,
		       first_seen, last_seen, observation_count, field_count,
		       required_field_count, fields, semantic_findings
		  FROM schema_registry
		 WHERE tenant_id = $1 AND source = $2 AND event_type = $3
		   AND declared_version <> $4
		 ORDER BY last_seen DESC
		 LIMIT 1`, tenantID, source, eventType, excludeVersion))
}

func loadSchemaEntryPool(
	ctx context.Context,
	store *PostgresStore,
	tenantID string,
	source string,
	eventType string,
	version string,
) (schema.RegistryEntry, error) {
	return scanSchemaEntryRow(store.pool.QueryRow(ctx, `
		SELECT tenant_id, source, event_type, declared_version, schema_url, fingerprint, health,
		       first_seen, last_seen, observation_count, field_count,
		       required_field_count, fields, semantic_findings
		  FROM schema_registry
		 WHERE tenant_id = $1 AND source = $2 AND event_type = $3 AND declared_version = $4`,
		tenantID, strings.TrimSpace(source), strings.TrimSpace(eventType), strings.TrimSpace(version)))
}

type schemaRow interface {
	Scan(dest ...any) error
}

func scanSchemaEntryRow(row schemaRow) (schema.RegistryEntry, error) {
	var entry schema.RegistryEntry
	var fieldsRaw []byte
	var semanticRaw []byte
	if err := row.Scan(
		&entry.TenantID, &entry.Source, &entry.EventType, &entry.DeclaredVersion,
		&entry.SchemaURL, &entry.Fingerprint, &entry.Health, &entry.FirstSeen, &entry.LastSeen,
		&entry.ObservationCount, &entry.FieldCount, &entry.RequiredFieldCount,
		&fieldsRaw, &semanticRaw,
	); err != nil {
		return schema.RegistryEntry{}, err
	}
	if err := json.Unmarshal(fieldsRaw, &entry.Fields); err != nil {
		return schema.RegistryEntry{}, fmt.Errorf("decode schema fields: %w", err)
	}
	if err := json.Unmarshal(semanticRaw, &entry.Semantic); err != nil {
		return schema.RegistryEntry{}, fmt.Errorf("decode schema semantic findings: %w", err)
	}
	return entry, nil
}

func scanSchemaEntry(rows interface{ Scan(dest ...any) error }) (schema.RegistryEntry, error) {
	entry, err := scanSchemaEntryRow(rows)
	if err != nil {
		return schema.RegistryEntry{}, fmt.Errorf("scan schema registry: %w", err)
	}
	return entry, nil
}

func upsertSchemaDriftTx(ctx context.Context, tx pgx.Tx, drift *schema.Drift) error {
	if drift.Signature == "" {
		drift.Signature = driftSignature(*drift)
	}
	_, err := tx.Exec(ctx, `
		INSERT INTO schema_drift_findings
			(tenant_id, source, event_type, declared_version, signature, severity,
			 kind, path, previous_type, current_type, message, first_seen, last_seen, occurrences)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,1)
		ON CONFLICT (tenant_id, source, event_type, declared_version, signature)
		DO UPDATE SET last_seen = EXCLUDED.last_seen,
		              occurrences = schema_drift_findings.occurrences + 1,
		              severity = EXCLUDED.severity,
		              message = EXCLUDED.message`,
		drift.TenantID, drift.Source, drift.EventType, drift.DeclaredVersion,
		drift.Signature, drift.Severity, drift.Kind, drift.Path,
		string(drift.PreviousType), string(drift.CurrentType), drift.Message,
		drift.FirstSeen, drift.LastSeen)
	if err != nil {
		return fmt.Errorf("upsert schema drift: %w", err)
	}
	return nil
}

func driftSignature(drift schema.Drift) string {
	raw := strings.Join([]string{
		drift.Kind, drift.Path, string(drift.PreviousType), string(drift.CurrentType), drift.Message,
	}, "|")
	sum := sha256.Sum256([]byte(raw))
	return hex.EncodeToString(sum[:12])
}
