// Command worker runs the TelemetryForge stream-processing consumer.
package main

import (
	"context"
	"log/slog"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"

	"github.com/fuhrdan/TelemetryForge/internal/logging"
	"github.com/fuhrdan/TelemetryForge/internal/stream"
	"github.com/fuhrdan/TelemetryForge/internal/worker"
)

func main() {
	logger := logging.New()
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	brokers := splitCSV(env("TELEMETRYFORGE_KAFKA_BROKERS", "localhost:9092"))
	topics := splitCSV(env("TELEMETRYFORGE_WORKER_TOPICS", "telemetry.raw,telemetry.metrics"))
	workers := envInt("TELEMETRYFORGE_WORKER_COUNT", 4)
	queueCapacity := envInt("TELEMETRYFORGE_WORKER_QUEUE_CAPACITY", 256)

	consumer, err := stream.NewKafkaConsumer(stream.ConsumerConfig{
		Brokers:  brokers,
		ClientID: env("TELEMETRYFORGE_WORKER_CLIENT_ID", "telemetryforge-worker"),
		GroupID:  env("TELEMETRYFORGE_WORKER_GROUP_ID", "telemetryforge-processors"),
		Topics:   topics,
	}, logger)
	if err != nil {
		logger.Error("create Kafka consumer", "error", err)
		os.Exit(1)
	}
	defer consumer.Close()

	pool, err := worker.NewPool(workers, queueCapacity, worker.Normalizer{}, logger)
	if err != nil {
		logger.Error("create worker pool", "error", err)
		os.Exit(1)
	}
	pool.Start(ctx)

	logger.Info("TelemetryForge worker started",
		"workers", workers, "queue_capacity", queueCapacity,
		"group_id", env("TELEMETRYFORGE_WORKER_GROUP_ID", "telemetryforge-processors"),
		"topics", strings.Join(topics, ","))

	if err := consumer.Run(ctx, pool); err != nil {
		logger.Error("consumer stopped with error", "error", err)
	}
	pool.Close()
	logger.Info("TelemetryForge worker stopped")
}

func env(name, fallback string) string {
	if value := strings.TrimSpace(os.Getenv(name)); value != "" {
		return value
	}
	return fallback
}

func envInt(name string, fallback int) int {
	value, err := strconv.Atoi(env(name, ""))
	if err != nil || value < 1 {
		return fallback
	}
	return value
}

func splitCSV(value string) []string {
	parts := strings.Split(value, ",")
	result := make([]string, 0, len(parts))
	for _, part := range parts {
		if part = strings.TrimSpace(part); part != "" {
			result = append(result, part)
		}
	}
	return result
}

// Keep slog imported in command documentation examples generated by godoc.
var _ *slog.Logger
