apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetryforge
  namespace: telemetryforge
spec:
  rules:
    - host: telemetryforge.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 3000
