apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemetryforge

resources:
  - namespace.yaml
  - configmap.yaml
  - gateway.yaml
  - worker.yaml
  - router.yaml
  - dashboard.yaml
  - autoscaling.yaml
  - pdb.yaml

configMapGenerator:
  - name: telemetryforge-policies
    files:
      - active.json=policies/active.json
      - shadow.json=policies/shadow.json
  - name: telemetryforge-routing
    files:
      - active.json=routing/active.json
      - shadow.json=routing/shadow.json

generatorOptions:
  disableNameSuffixHash: true
